### ISSUE TITLE
Iterative Pagination

### ISSUE THREAD

**Issue by MikeVL** [blacklocus/angular-django-rest-resource#6]
Why djResource fetch all pages if result is paginated?

How i can fetch pages on demand?

**Comment by JustinTArthur** [comment]
Currently, `djResource` does not support opting out of auto-pagination when it receives object-encapsulated list responses with a `next` property.

As a workaround, I suggest creating a custom pagination serializer for your view that uses a property named something other than `next` as its `NextPageField`. See [this paragraph](http://www.django-rest-framework.org/api-guide/pagination#custom-pagination-serializers) for a quick guide on creating a custom pagination serializer.

It does sound reasonable to want to support on-demand iteration of result pages, so I'll leave this ticket open as an enhancement request for such a feature. Thanks!

**Comment by rsaikali** [comment]
:+1:

**Comment by anton-107** [comment]
+1 this is somewhat unexpected/confusing behavior

**Comment by AdrianRibao** [comment]
+1 for this issue.

If the API returns thousands of objects, it can be a problem because we would need too many http requests, and we are forced to wait for a long time before the results are rendered.

If we can opt-out the auto-pagination feature, we still need a way to deal with pagination.

I'm just learning angular and I don't even understand the full resource code, I wish I could help you with this.

I'm totally stuck with this issue. If I use a custom pagination, how could I request the next page? or get the number of pages available for creating a nice paginator?

**Comment by ashleyblackmore** [comment]
This would be an awesome feature, but it needs someone with enough knowledge of angular + django rest framework to take it on

**Comment by ashleyblackmore** [comment]
Okay I had a look at this. I don't think the recursivePaginator serves everyone's expectations. The workaround (to build on @JustinTArthur's comment above) for me was to simply make an empty CustomPaginationSerializer (just override BasePaginationSerializer then pass), and add that to your generic view. This way you avoid including 'count' in your resource, and so you never hit the paginator. You can then go on and request more pages manually, as need be. You will also need to transform the response, mid-flight, in your services, like:

```
            query:  {method: 'GET',
                     transformResponse: function(data, headers){
                         data = angular.fromJson(data);
                         data = data.results;
                         return data;
                     },
                     isArray: true
                },
```

Ugh. I'd still like to add on-demand pagination to this code, because in every other way it is fantastic.

**Comment by scholtalbers** [comment]
Any chance this will get implemented? I will be dealing with multiple thousands of rows and I plannig to use angular ui-grid with external pagination done by DRF.
