### ISSUE TITLE
An injection example would be very helpful

### ISSUE THREAD

**Issue by jobelenus** [blacklocus/angular-django-rest-resource#7]
For those of us who are coming on to angularjs and don't have the history of the project down, figuring out how to inject the djResource/get at it, as per the style they use in the tutorial, is not easy. I still haven't been able to do it.

I'm stuck here: https://gist.github.com/jobelenus/9103118

What am I doing wrong/missing?

**Comment by JustinTArthur** [comment]
Hey, @jobelenus. I think you've just got a simple mismatch of the module and service here. In this case, you're listing `djResource` as a module dependency instead of an injected service. The module name is actually `djangoRESTResources`. In your gist, you label `djangoRESTResources` module as a dependency for the app module, but if you're only going to use `djResource` inside your `appServices` module, just list it there instead (where you currently list `djResource`).

Then, in that service you're defining, you can inject `djResource` alongside or replacing the `$resource` service that you're currently injecting.

Here's your gist, forked and adjusted: https://gist.github.com/JustinTArthur/9103236

I agree with you on needing a better example. I hope to have a test case directory at some point with both an example Django project and simple AngularJS app.

**Comment by jobelenus** [comment]
Aha! OK I was misunderstanding what "level" (a very bad word/metaphor) the injections were happening on. I suspected that `djangoRESTResources` at the app/module "level" was making `djResource` available elsewhere for direct injection. This is literally day 1 with angular, but I wanted to make sure that both the "ending-slash" problem and the "let-rest-framework-handle-pagination" could both get solved right out the gate. I admit I don't fully grasp this lazy-load/injection style quite yet. It's a head scratcher, but powerful.

Thanks!
